### ISSUE TITLE
Dynamically calculate the minimum and maximum values that the `readSensors()` function can return.

### ISSUE THREAD

**Issue by ErickSimoes** [garagino/Followline#10]
Currently these values are defined as a magic number, but it is possible to know its maximum value from `SensorCount`.

The formula is:
`(SensorCount - 1) * 1000`

**Comment by andrewkfa** [comment]
This actually is not an issue. It returns almost 10 bits of data from the lecture of each sensor individually, that is quite enough, so what's the idea to change it to put other values?

**Comment by ErickSimoes** [comment]
The issue is that the magic number is `7000`, which appears in this code snippet:

`error = map(readSensors(), 0, 7000, -1000, 1000);`

This number is a result of the number of sensors we are using, so we can define it dynamically based on the size of the sensor array.

More about that here:
https://sites.google.com/a/cabrillo.edu/cs-11m/howtos/cppdoc#TOC-Limit-Magic-Numbers
